on:
  schedule: [{cron: "*/7 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  status:
    runs-on: ubuntu-latest
    name: Update Discord Status
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Checkout files
        uses: actions/checkout@v4.1.0
      - name: Update Status
        uses: CompeyDev/discord-status-action@0.2.4
        with:
          file: README.md
          id: "893762371770802227" # Replace with your Discord User ID
      - name: Commit and push if there are changes
        run: |-
          git diff
          git config --global user.email "joannanthaniel@gmail.com" # Replace with an email associated to your GitHub Account.
          git config --global user.name "JuanNathaniel"
          git diff --quiet || (git add -u && git commit -m "🚀 Update Discord Status")
          git push               
